apiVersion: v1
kind: ServiceAccount
metadata:
  name: foodgram-deployer
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foodgram-deployer
  namespace: foodgram
rules:
  - apiGroups: ["", "apps", "batch", "autoscaling", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: foodgram-deployer
  namespace: foodgram
subjects:
  - kind: ServiceAccount
    name: foodgram-deployer
    namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foodgram-deployer
