githubConfigUrl: "https://github.com/A7med373/django_5sem"
githubConfigSecret: "foodgram-runner-github-token"

runnerScaleSetName: "foodgram"
minRunners: 1
maxRunners: 2

containerMode:
  type: "dind"

template:
  spec:
    serviceAccountName: "foodgram-deployer"
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command:
          - /home/runner/run.sh
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
