apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.configMap }}
  {{- if and (eq $key "DB_HOST") (or (not $val) (eq $val "")) }}
  DB_HOST: {{ printf "postgres-service.%s.svc.cluster.local" $.Release.Namespace | quote }}
  {{- else }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
